stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pytest
  tags:
    - docker
    - mcs

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=$HOSTING_NAME --app=$HOSTING_APP_NAME --api-key=$HOSTING_API_KEY
  tags:
    - docker
    - mcs
  only:
    - master