stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pytest
  tags:
    - docker

deploy:
  stage: deploy
  image: ruby:2.6.5-buster
  environment:
    name: production
    url: https://tarantool-rocks.herokuapp.com
  when: manual
  only:
    - master
  before_script:
    - gem install dpl-heroku
  script:
    - dpl --provider=heroku --app=tarantool-rocks --api-key=$HOSTING_API_KEY
  tags:
    - docker
