stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pytest
  tags:
    - heroku
    - mcs

deploy:
  stage: deploy
  image: ruby:2.2
  script:
    - gem install dpl
    - dpl --provider=$HOSTING_NAME --app=$HOSTING_APP_NAME --api-key=$HOSTING_API_KEY
  tags:
    - heroku
    - mcs
  only:
    - master