name: 'Upload rocks'
description: 'Upload a rock to the https://rocks.tarantool.org'
inputs:
  auth:
    description: 'Credentials for the rocks server authentication'
    required: true
  files:
    description: 'A list of rocks to upload'
    required: true
  rocks-server:
    description: 'Custom rocks server URL'
    default: 'https://rocks.tarantool.org'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: set -x;
        FILES="${{ inputs.files }}";
        for F in $FILES; do
          curl --fail
          -u ${{ inputs.auth }} ${{ inputs.rocks-server }}
          -X PUT -F "rockspec=@$F";
        done
