name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - run: gem install dpl-heroku
      - run: dpl
          --provider=heroku
          --app=tarantool-rocks
          --api-key=${{ secrets.DEPLOYMENT_API_KEY }}
